annotations:
  min_scale_version: 24.10.2.2
app_version: 13.0.0
capabilities: []
categories:
  - file sharing
  - collaboration
changelog_url: https://manual.seafile.com/changelog/
description: Seafile is a high-performance file sync and share platform for teams.
home: https://www.seafile.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/seafile/icons/icon.png
keywords:
  - files
  - sync
  - sharing
  - collaboration
lib_version: 2.1.65
lib_version_hash: f92a9ee78c78fc77f86e7d8b545bd4c605c31c599e2c5da59f1615aa516cb8b5
maintainers:
  - name: TrueNAS Community
    email: apps@truenas.com
name: seafile
run_as_context:
  - description: Seafile services run as non-root.
    uid: 568
    gid: 568
    user_name: seafile
    group_name: seafile
screenshots: []
sources:
  - https://manual.seafile.com/13.0/setup/setup_ce_by_docker/
  - https://hub.docker.com/r/seafileltd/seafile-mc
title: Seafile
train: community
version: 1.0.0
